### ISSUE TITLE
auto_arima - start_p, start_q ignored when non-stepwise

### ISSUE THREAD

**Issue by orvindell** [alkaline-ml/pmdarima#338]
Firstly - thanks a lot for making such a cool tool :) 

I'm a newbie, trying to use auto-arima for a basic implementation and run into some issues, I'm not sure if it's a malfunction of the API or my lack of understanding and hope you could help me:

no.1 cannot get the start_p and start_q to work as expected, they're being always ignored and 0's are used as starting values. 
Here my code
`#ARIMAImplementation
arima_model = auto_arima(train_data, m=10, start_p=2, start_q=2,
                           start_P=0, start_Q=0, seasonal=False,
                           d=1, max_D=1, trace=True, stepwise=False)`
The first model fitted is:
"Fit ARIMA(0,1,0)x(0,0,0,0) [intercept=True]; AIC=17645.253, BIC=17655.436, Time=0.060 seconds"

I expect it to start with:
Fit ARIMA(**2**,1,**2**)x(0,0,0,0)

no. 2 

At the moment, the last checked combination is: 
Fit ARIMA(5,1,0)x(0,0,0,0) [intercept=True]; AIC=17646.485, BIC=17682.127, Time=0.318 seconds

Since by default, max_p & max_q = 5  I expect the grid search to also reach a combination:
Fit ARIMA(**5**,1,**4**)x(0,0,0,0)  etc. 

full log
[auto_arimalogs.txt](https://github.com/alkaline-ml/pmdarima/files/4646568/auto_arimalogs.txt)

pmdarima-1.6.0

Edit: I see that the version now updated to 1.6.1, but the ?issue? persists

I mistakenly used the old version of the library before "pyramid-arima" and then both of the issues didn't exist. Moreover, the best combination for the same data then was exactly (5,1,4) which now does not get checked.

**Comment by tgsmith61591** [comment]
Ah, very good question. We used to use `start_p` for random search, but as of later versions switched random searches to starting at zero. See [this line](https://github.com/alkaline-ml/pmdarima/blob/master/pmdarima/arima/auto.py#L510). This is because Hyndman in the R package starts random searches at 0, and we wanted to more closely align with that behavior. Stepwise searches, however, first use `start_p` and `start_q` before exploring other model combinations.

It's really important to note that `stepwise=False` is essentially a random grid search. The stepwise algorithm is typically always preferred. Another thing to note is that `max_order` (default 5) plays a role. In an effort to avoid overfitting, this limits the order (sum of `[p, q]` or `[p, q, P, Q]` for seasonal models) from growing too large. You can always ignore that by setting `max_order` to None.

Finally, and unrelated to your question, `P`, `D`, `Q` and `m` are seasonal parameters. Since you set seasonal to False, you don't need them. Try this out and see if you get your expected model:

```python
arima_model = auto_arima(
    train_data, start_p=2, start_q=2, seasonal=False, d=1,
    trace=True, stepwise=False, max_order=None)
```

I'd also be interested to see how the stepwise search does for you. It would probably be faster.

**Comment by tgsmith61591** [comment]
Closing since I believe this is resolved.
