### ISSUE TITLE
How can I specify different trends?

### ISSUE THREAD

**Issue by MatthiasHerp** [alkaline-ml/pmdarima#365]
Hello,
I have a short Question concerning Trends in the "auto_arima" command.
Suprisingly I couldn't find anything in other issues, the documentation or blog Posts, so ist probably obvious but I'm not getting it :)

In the statmodels documentation I read that in their ARIMA the trend is either equal "c" which is a constant or "nc" which is no constant. In "auto_arima" the constant is however handled by "with_intercept" which if "True" includes a constant.

Thus my Question is, how can a trend be included into the model? And if the trend component should be used, as is suggested in the exogenous part of the documentation "This should not include a constant or trend", what kinds of strings can be used to apply different trend methods.
Further, can the trend be modelled customly, as i would like to include a linear trend , with trend shifts (slope changes)?

Thank a lot for your help and time.

**Comment by tgsmith61591** [comment]
Hey there, you can provide the `trend` argument to the `auto_arima` function:

https://github.com/alkaline-ml/pmdarima/blob/master/pmdarima/arima/auto.py#L310

The `with_intercept` method takes some of the work out of it for the user. If `trend` is not provided, but `with_intercept` is, we just set it to `'c'` so we fit a constant. But if you provide `trend`, it should fit the model with what you've provided. Does that answer your question?

**Comment by MatthiasHerp** [comment]
Hey @tgsmith61591 , thanks for the reply. My last open Question is how do i provide a "custom" trend? So what option due users have besides 'nc' and 'c'?
Because the way I understood you, setting with intercept 'True' or setting trend to 'c' results in the same, a constant. Thus why are there two commands? 

Thanks again :)

**Comment by tgsmith61591** [comment]
> how do i provide a "custom" trend?

Pass `trend=whatever`. You can only use the options statsmodels supports: `{‘n’,’c’,’t’,’ct’}`

> the way I understood you, setting with intercept 'True' or setting trend to 'c' results in the same, a constant. Thus why are there two commands?

One of the things we manipulate in the search is whether to fit with a constant (i.e., trend='c'), like R does. In the old days the ARIMA class encapsulated one of a few statsmodels classes, and the same trend options did not hold for all classes, so setting `with_intercept` was equal to `trend='c'` for one class, and something different for another. After moving everything over to sarimax, it's slightly redundant. If we were to remove it we'd need several minor release cycles with a deprecation warning since removing an arg from a public function that people are using is not very friendly

**Comment by MatthiasHerp** [comment]
Thank you very much :)
