### ISSUE TITLE
ImportError: cannot import name 'six' from 'sklearn.externals' (g:\Users\CHINNI\Anaconda3\lib\site-packages\sklearn\externals\__init__.py)

### ISSUE THREAD

**Issue by chinnijyothsna** [alkaline-ml/pmdarima#433]
getting this error while importing imblearn package

**Comment by aaronreidsmith** [comment]
Hi, thanks for the issue. In the future please fill out our  issue template and search through old issues to see if your question was already asked; at first glance, this issue has nothing to do with `pmdarima` (we are not affiliated with `imblearn`).

Since you are using conda, this is likely a duplicate of #375.  We only support a `pip` installation. There are several people who have republished the package on `conda`, but we are not affiliated with them and do not officially support/test conda installs. You can do the following to install from pip.

```
conda remove pmdarima
pip install pmdarima
```
