### ISSUE TITLE
Setting `m` for Stock Market Predictions

### ISSUE THREAD

**Issue by Alpheron** [alkaline-ml/pmdarima#485]
### Describe the question you have

Hello,

I am trying to perform time-series forecasting on stock market data. However, the "Setting M" documentation says that `m` should be set to the number of observances per seasonal cycle. Stock Market data is recorded 253 times a year, so does that mean `m` should be set to 253?

**Comment by sonicpierre** [comment]
Hello,

From my point of view m is the period for seasonal differencing. As you know to predict your stock market it needs to be stationary and that's why you need differenciation. To set it you just need to know what is your seasonal order, here if you have yearly seasonality you can put m = 12. Hope it'll help.

**Comment by tgsmith61591** [comment]
Yes this is not something that can be set unilaterally, it depends on you, the model developer to have an understanding of your data. Please see [this section](https://alkaline-ml.com/pmdarima/tips_and_tricks.html#setting-m) of the documentation to understand `m` better.

@sonicpierre is correct that the stock market data may not be seasonal (I am not your financial advisor 😃 ; take this with a grain of salt), and `m` depends completely on your data.
