### ISSUE TITLE
 pmdarima about Quickstart program 3.1. Auto-ARIMA example

### ISSUE THREAD

**Issue by n-matsukawa** [alkaline-ml/pmdarima#508]
### Describe the question you have

Hello everyone. My name is Norifumi.
I am trying  auto_arima with pdmarima lib.
I see web (https://alkaline-ml.com/pmdarima/quickstart.html).
But my summary is not same web result.
I try 2type OS(win,mac).
Please tell me that this difference cause.
I attach 3 files.
sample3_1.txt
Result_Windows10OS.txt                                     
Result_macOS.txt
[sample3_1.txt](https://github.com/alkaline-ml/pmdarima/files/8904894/sample3_1.txt)
[Result_Windows10OS.txt](https://github.com/alkaline-ml/pmdarima/files/8904896/Result_Windows10OS.txt)
[Result_macOS.txt](https://github.com/alkaline-ml/pmdarima/files/8904899/Result_macOS.txt)

**Comment by tgsmith61591** [comment]
What version of statsmodels are you on? My guess would be difference in version could yield very slight differences in AIC scores which would cause models to sort differently.

**Comment by n-matsukawa** [comment]
Thank you Taylor G Smith.
I use  statsmodels version below.
Window10 statsmodels 0.13.2
MacOS statsmodels 0.13.2
Best regards

**Comment by tgsmith61591** [comment]
Ok, I see the issue here. The quickstart doc you reference is one of few static examples we have, and has not been regenerated since v1.0.0 (3.5 years ago). We'll update that doc, as the version of statsmodels used back then was vastly different. Your results match what I get on the latest version of statsmodels.
